name: MDP Python Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'py/**'
      - '.github/workflows/py.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'py/**'
      - '.github/workflows/py.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup uv
      uses: astral-sh/setup-uv@v2

    - name: Install dependencies
      run: uv pip install --system ruff

    - name: Run linting
      run: ruff check .

  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup uv
      uses: astral-sh/setup-uv@v2

    - name: Install dependencies
      run: uv pip install --system mypy

    - name: Run type checks
      run: mypy . --ignore-missing-imports

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup uv
      uses: astral-sh/setup-uv@v2

    - name: Install dependencies
      run: uv pip install --system pytest pytest-cov kaitaistruct

    - name: Run unit tests
      run: |
        mkdir -p test-results
        pytest --cov=mdp_m01 --cov-report=term --cov-report=xml:coverage.xml --junitxml=test-results/junit.xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./py/coverage.xml
        flags: unittests
        name: codecov-mdp-python
        fail_ci_if_error: false

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: python-test-results
        path: |
          py/test-results/
          py/coverage.xml
        retention-days: 7
        if-no-files-found: warn

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [lint, type-check, unit-tests]
    if: always()

    steps:
    - name: Check job statuses
      run: |
        if [[ "${{ needs.lint.result }}" != "success" || "${{ needs.type-check.result }}" != "success" || "${{ needs.unit-tests.result }}" != "success" ]]; then
          echo "One or more CI checks failed"
          echo "Lint: ${{ needs.lint.result }}"
          echo "Type Check: ${{ needs.type-check.result }}"
          echo "Unit Tests: ${{ needs.unit-tests.result }}"
          exit 1
        else
          echo "All CI checks passed successfully!"
        fi
